name: DotaMarket.RepositoryTests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: DotaMarket.sln
      Test_Project_Path: DotaMarket.DataLayer.Tests\DotaMarket.DataLayer.Tests.csproj

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build $env:Solution_Name

    - name: Test
      run: dotnet test $env:Test_Project_Path
